# Seed 15 Data
name: 'WebQuestions'
data_dir: './data/'
train_data: 'train_vec.json'
valid_data: 'valid_vec.json'
test_data: 'test_vec.json'
pre_word2vec: './data/glove_pretrained_300d_w2v.npy'

# Full vocab
vocab_size: 100797
num_ent_types: 1712
num_relations: 4996

num_query_words: 10

# Output
model_file: './models/bamnet.md'

# Model
query_size: 32
query_markup_size: 1 # Not used
ans_bow_size: 1 # Not used
ans_path_bow_size: null
ans_ctx_entity_bow_size: 6

vocab_embed_size: 300
hidden_size: 128
o_embed_size: 128
mem_size: 96
word_emb_dropout: 0.3
que_enc_dropout: 0.3
ans_enc_dropout: 0.2
attention: 'add'
num_hops: 1

# Training
learning_rate: 0.001
batch_size: 32
num_epochs: 2
valid_patience: 10
margin: 1

# Testing
test_batch_size: 1
test_margin:
        - 0.7

# Device
no_cuda: false
gpu: 0
